engines:
  eslint:
    enabled: true
  stylelint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - javascript
        - typescript
        - vue
  complexity:
    enabled: true
    config:
      languages:
        - javascript
        - typescript
        - vue

exclude_paths:
  # Build outputs
  - build/
  - dist/
  - .next/
  - .nuxt/
  - .output/
  - .cache/
  - .data/
  - .tmp/
  # Dependencies
  - node_modules/
  # Git
  - .git/
  # IDE
  - .vscode/
  # Public assets
  - public/
  # Database
  - database/
  - exports/
  # Strapi specific
  - apps/strapi/.tmp/
  - apps/strapi/build/
  # Website specific
  - apps/website/.nuxt/
  - apps/website/.output/
  - apps/website/.data/
  # Dashboard specific (Nuxt)
  - apps/dashboard/.nuxt/
  - apps/dashboard/.output/

ignore:
  - "**/*.test.js"
  - "**/*.spec.js"
  - "**/*.test.ts"
  - "**/*.spec.ts"
  - "**/*.test.vue"
  - "**/*.spec.vue"
  - "**/tests/**"
  - "**/__tests__/**"
  - "**/__snapshots__/**"
  - "**/cypress/**"
  - "**/*.config.js"
  - "**/*.config.ts"

