#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

yarn format
yarn lint-staged

# Si hay cambios después del lint-staged, agregarlos al commit actual
if ! git diff --cached --quiet; then
  git add .
fi
