engines:
  eslint:
    enabled: true
  stylelint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - javascript
        - typescript
  complexity:
    enabled: true
    config:
      languages:
        - javascript
        - typescript

exclude_paths:
  - build/
  - dist/
  - node_modules/
  - .cache/
  - .git/
  - .tmp/
  - .vscode/
  - public/
  - database/
  - exports/

ignore:
  - "**/*.test.js"
  - "**/*.spec.js"
  - "**/*.test.ts"
  - "**/*.spec.ts"
  - "**/tests/**"
  - "**/__tests__/**"
